apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kplabs-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
      containers:
      - name: kplabs-pods
        image: busybox
        args:
        - /bin/sh
        - -c 
        - date; echo Hello From k8s
      restartPolicy: OnFailure 
  