apiVersion: batch/v1
kind: Job
metadata:
  name: job 
spec:
  template:
    spec:
      containers:
      - name: kplabs-pods
        image: busybox
        command: ["bin/sh"] 
        args: ["-c", "echo HelloWorld"]
      restartPolicy: Never  
