apiVersion: v1
kind: Pod 
metadata: 
  name: livness
spec: 
  containers:
  - image: ubuntu
    name: livness-probe
    tty: true
    livenessProbe:
      exec:
        command: 
        -  service 
        -  nginx 
        -  status 
      initialDelaySeconds: 20
      periodSeconds: 5